/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#e1e3e4",
        "surface-tint": "#bbc7de",
        "outline": "#8f9097",
        "tertiary-fixed": "#d6e3ff",
        "primary-fixed-dim": "#bbc7de",
        "surface-dim": "#111415",
        "inverse-surface": "#e1e3e4",
        "inverse-on-surface": "#2e3132",
        "background": "#111415",
        "secondary": "#fff9ef",
        "on-tertiary-fixed": "#091c35",
        "on-secondary-fixed-variant": "#544600",
        "primary-fixed": "#d7e3fb",
        "tertiary-fixed-dim": "#b7c7e9",
        "surface-container-low": "#191c1d",
        "on-secondary-fixed": "#221b00",
        "on-surface": "#e1e3e4",
        "surface-container-high": "#282a2b",
        "primary": "#bbc7de",
        "on-error-container": "#ffdad6",
        "on-tertiary": "#20314b",
        "surface-container": "#1d2021",
        "on-surface-variant": "#c5c6cd",
        "on-primary-fixed-variant": "#3c475a",
        "surface-variant": "#323536",
        "surface-bright": "#373a3b",
        "on-error": "#690005",
        "on-secondary": "#3a3000",
        "secondary-container": "#ffdb3c",
        "outline-variant": "#44474c",
        "tertiary-container": "#02142d",
        "surface": "#111415",
        "on-tertiary-container": "#6f7f9e",
        "on-primary": "#263143",
        "surface-container-highest": "#323536",
        "on-tertiary-fixed-variant": "#374763",
        "surface-container-lowest": "#0c0f10",
        "inverse-primary": "#545f73",
        "error-container": "#93000a",
        "error": "#ffb4ab",
        "primary-container": "#081425",
        "tertiary": "#b7c7e9",
        "on-primary-fixed": "#101c2d",
        "secondary-fixed-dim": "#e9c400",
        "on-primary-container": "#737f94",
        "secondary-fixed": "#ffe16d",
        "on-secondary-container": "#725f00",
        "gold": "#FFD700",
        "luxury-blue": "#12233D",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "80px",
        unit: "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        gutter: "24px",
      },
      fontFamily: {
        sans: ["Manrope", "sans-serif"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
        "label-caps": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "body-md": ["Manrope"],
        "body-lg": ["Manrope"],
        "display-lg": ["Manrope"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
